"""
Query Engine for Translating Structured JSON to SQL

This module is responsible for taking a structured JSON query,
as generated by a function-calling LLM, and safely translating it
into an executable SQL query.
"""

import json
from typing import Dict, Any, List, Optional

def _validate_query_structure(query: Dict[str, Any]) -> bool:
    """Validate the basic structure of the incoming JSON query."""
    required_keys = ['operation', 'table']
    if not all(key in query for key in required_keys):
        raise ValueError("Query must contain 'operation' and 'table' keys")
    
    if query['operation'] not in ['search', 'aggregate']:
        raise ValueError("Invalid operation specified")
        
    return True

def _build_where_clause(filters: Optional[List[Dict[str, Any]]]) -> (str, List[Any]):
    """Build the WHERE clause and parameters from a list of filters."""
    if not filters:
        return "", []
    
    conditions = []
    params = []
    
    for f in filters:
        field = f.get('field')
        operator = f.get('operator', '=').upper()
        value = f.get('value')
        
        if not field or value is None:
            continue
            
        # Basic validation for operators
        allowed_ops = ['=', '!=', '>', '<', '>=', '<=', 'LIKE', 'IN']
        if operator not in allowed_ops:
            raise ValueError(f"Unsupported operator: {operator}")
            
        if operator == 'IN':
            if not isinstance(value, list):
                raise ValueError("IN operator requires a list value")
            placeholders = ', '.join(['?'] * len(value))
            conditions.append(f"{field} IN ({placeholders})")
            params.extend(value)
        else:
            conditions.append(f"{field} {operator} ?")
            params.append(value)
            
    where_clause = " WHERE " + " AND ".join(conditions) if conditions else ""
    return where_clause, params

def translate_json_to_sql(query: Dict[str, Any]) -> (str, List[Any]):
    """
    Translate a structured JSON query object into an executable SQL query string
    and a list of parameters for safe execution.
    """
    _validate_query_structure(query)
    
    table = query['table']
    operation = query['operation']
    
    # Basic table name validation to prevent injection
    if not table.isalnum() and '_' not in table:
        raise ValueError(f"Invalid table name: {table}")
    
    params = []
    
    if operation == 'search':
        select_fields = query.get('select_fields', ['*'])
        fields_str = ', '.join(select_fields)
        
        filters = query.get('filters')
        where_clause, where_params = _build_where_clause(filters)
        params.extend(where_params)
        
        limit = query.get('limit')
        limit_clause = f" LIMIT {int(limit)}" if limit else ""
        
        sql = f"SELECT {fields_str} FROM {table}{where_clause}{limit_clause};"
        
    elif operation == 'aggregate':
        aggregation_field = query.get('aggregation_field')
        aggregation_type = query.get('aggregation_type', 'AVG').upper()
        
        if not aggregation_field:
            raise ValueError("Aggregation operation requires 'aggregation_field'")
        
        filters = query.get('filters')
        where_clause, where_params = _build_where_clause(filters)
        params.extend(where_params)
        
        group_by = query.get('groupBy')
        group_by_clause = f" GROUP BY {group_by}" if group_by else ""
        
        sql = f"SELECT {aggregation_type}({aggregation_field}) FROM {table}{where_clause}{group_by_clause};"
        
    else:
        raise ValueError(f"Unsupported operation type: {operation}")
        
    return sql, params 